# Generated by Django 3.1.2 on 2021-01-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogUser',
        ),
    ]
