# Generated by Django 3.1.7 on 2021-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_number', models.IntegerField()),
                ('date_begin', models.DateField(unique=True)),
                ('date_end', models.DateField(unique=True)),
            ],
        ),
    ]
